import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Dashboard from "../components/Dashboard/Dashboard";
import Loader from "../components/Loader/Loader";

const Home = () => {
  const router = useRouter();

  const { status } = useSession({
    // If the user is not authenticated, then redirect to the login page
    onUnauthenticated() {
      router.push("/auth/signin");
    },
  });

  // Meaning the user is not logged in or is being logged in
  if (status === "loading") return <Loader></Loader>;

  // Returned only when the user is logged in
  return (
    <div>
      <Head>
        <title>Spotify Redesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard></Dashboard>
    </div>
  );
};

export default Home;
