import Head from "next/head";
import Image from "next/image";
import Dashboard from "../components/Dashboard/Dashboard";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Spotify Redesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard></Dashboard>
    </div>
  );
};

export default Home;
